### PR TITLE
Remove explicit export name choosing

### PR DESCRIPTION
**Pull request by choffmeister**
Gives the user just a folder selection dialog and addes the filename and
extension automatically.

Relates to #2

### CODE REVIEW

**Comment by choffmeister** [comment]
@wjramos @mknris Please check out, if this solves your issues.

**Comment by mknrls** [comment]
@choffmeister perfect it works :D

**Comment by mknrls** [comment]
this if statement wont be needed anymore like now the extension is set automatically.

```javascript 
 if (!file || !file.toString().match(/\.icns$/)) {
    alert('You must choose an .icns file');
    return;
  }
```

**Comment by mknrls** [comment]
@choffmeister i did some more testing with the script and found a other issue, not serious tho. 

Let say i was going to export the icns but decided last minute decided to cancel it (close the Choose Folder dialog) this error would appear:

error_icns_export

**Comment by choffmeister** [comment]
Thanks. This should now be fixed.

**Comment by mknrls** [comment]
@choffmeister no problem :+1: There is one more. If the icon name contains spaces the export message dialog displays the spaces as %20. I think the last bug, didn't see any more. 

Thanks for improving this, really appreciate. I would've help out but kinda sucks at JavaScript at the moment.

**Comment by choffmeister** [comment]
Now? :)

**Comment by mknrls** [comment]
Fix :D

**Comment by mknrls** [comment]
is there a way for the illustrator file to stop thinking that it is being modify after being exported? (just wondering ?

**Comment by choffmeister** [comment]
Good question. Don't know. If this is a real issue, please start an issue for that. When I have time I can look around for an answer.

**Pull request merged**
